import { readFileSync, writeFileSync } from "node:fs";

const [srcPath, outPath] = process.argv.slice(2);
if (!srcPath || !outPath) {
    console.error("usage: embed.ts <in.ts> <out.c>");
    process.exit(1);
}

const buf = readFileSync(srcPath);
const lines: string[] = [];
for (let i = 0; i < buf.length; i += 16) {
    lines.push("    " + Array.from(buf.subarray(i, i + 16)).join(","));
}

writeFileSync(
    outPath,
    "/* generated by tools/embed.ts - do not edit */\n" +
        "unsigned char ts_bundle[] = {\n" +
        lines.join(",\n") +
        "\n};\n" +
        "unsigned int ts_bundle_len = " +
        buf.length +
        ";\n"
);
